ProyectoVikingsGen/MvcApplication1/Controllers/BatallaPVPController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

using ProyectoVikingsGenNHibernate.CAD.ProyectoVikings;
using ProyectoVikingsGenNHibernate.CEN.ProyectoVikings;
using ProyectoVikingsGenNHibernate.CP.ProyectoVikings;
using ProyectoVikingsGenNHibernate.EN.ProyectoVikings;

namespace MvcApplication1.Controllers
{
    [Authorize(Roles = "usuario")]
    public class BatallaPVPController : BasicController
    {
        //
        // GET: /BatallaPVP/

        public ActionResult Index()
        {
            SessionInitialize();
            Batalla_PVPCAD cad = new Batalla_PVPCAD(session);
            var aux = cad.ReadAllDefault(0, 0);

            SessionClose();

            return View(aux);
        }

        //
        // GET: /BatallaPVP/Details/5

        public ActionResult Details(int id)
        {
            Batalla_PVP ev = null;
            SessionInitialize();
            Batalla_PVPEN evEN = new Batalla_PVPCAD(session).ReadOIDDefault(id);
            ev = new AssemblerBatalla_PVP().ConvertEnToModelUI(evEN);
            SessionClose();
            return View(ev);
        }

        //
        // GET: /BatallaPVP/Create

        public ActionResult Create()
        {

            SessionInitialize();
            //muy posiblemente si falla, es por esto
            Batalla_PVP ev = new Batalla_PVP();
            ev.Jugador.Nombre = User.Identity.Name;

            SessionClose();
            return View(ev);
        }

        //
        // POST: /BatallaPVP/Create

        [HttpPost]
        public ActionResult Create(Batalla_PVP ev)
        {
            try
            {
                JugadorCAD cad = new JugadorCAD();
                Batalla_PVPCEN cen = new Batalla_PVPCEN();
                Batalla_PVPEN even = new Batalla_PVPEN();
                even.Jugador_0 = ev.Jugador2;
                even.Recompensa = ev.Recompensa;
                even.IdGanador = ev.IdGanador;

                even.Jugador = cad.DameJugadorPorNombre(User.Identity.Name);
                cen.New_(even.Jugador.Id, even.Jugador_0.Id, ev.Recompensa, ev.IdGanador);

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }


        //
        // GET: /Batalla_PVP/Edit/5

        public ActionResult Edit(int id)
        {
            Batalla_PVP ev = null;
            SessionInitialize();
            Batalla_PVPEN even = new Batalla_PVPCAD(session).ReadOIDDefault(id);
            ev = new AssemblerBatalla_PVP().ConvertEnToModelUI(even);
            JugadorEN usu = ev.Jugador;
            if (User.Identity.Name != usu.Nombre && !Roles.IsUserInRole("admin"))
            {
                return RedirectToAction("Details", new { id = id });
            }
            SessionClose();
            return View(ev);

        }

        //
        // POST: /Batalla_PVP/Edit/5

        [HttpPost]
        public ActionResult Edit(Batalla_PVP ev)
        {
            try
            {
                Batalla_PVPCEN cen = new Batalla_PVPCEN();

                cen.Modify(ev.id, ev.Recompensa, ev.IdGanador);
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Batalla_PVP/Delete/5

        public ActionResult Delete(int id)
        {
            Batalla_PVP ev = null;
            SessionInitialize();
            Batalla_PVPEN even = new Batalla_PVPCAD(session).ReadOIDDefault(id);
            ev = new AssemblerBatalla_PVP().ConvertEnToModelUI(even);
            JugadorEN usu = ev.Jugador;
            if (User.Identity.Name != usu.Nombre && !Roles.IsUserInRole("admin"))
            {
                return RedirectToAction("Details", new { id = id });
            }
            SessionClose();
            return View(ev);
        }

        //
        // POST: /Batalla_PVP/Delete/5

        [HttpPost]
        public ActionResult Delete(Batalla_PVP ev)
        {
            try
            {

                Batalla_PVPCEN cen = new Batalla_PVPCEN();
                cen.Destroy(ev.id);


                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Batalla_PVP/List

        public ActionResult List()
        {
            SessionInitialize();
            Batalla_PVPCAD cad = new Batalla_PVPCAD(session);
            JugadorCAD usucad = new JugadorCAD(session);
            JugadorEN usuen = usucad.DameJugadorPorNombre(User.Identity.Name);
            var aux = cad.ReadAllDefault(0, 0);
            SessionClose();

            return View(aux);
        }
    }
}

ProyectoVikingsGen/MvcApplication1/Views/BatallaPVP/Create.cshtml
@model MvcApplication1.Models.Batalla_PVP

@{
    ViewBag.Title = "Nuevo BatallaPVP";
}

<h2>Nuevo BatallaPVP</h2>

@using (Html.BeginForm("Create", "BatallaPVP", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    //id, recompensa, tipoGanador
    <fieldset>
        <legend>BatallaPVP</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.id)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.id)
            @Html.ValidationMessageFor(model => model.id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Recompensa)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Recompensa)
            @Html.ValidationMessageFor(model => model.Recompensa)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdGanador)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdGanador)
            @Html.ValidationMessageFor(model => model.IdGanador)
        </div>

     
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<!--h3>Mapa</h3>-->

<div>
    @Html.ActionLink("Volver a BatallaPVPs", "Index")
</div>

@section Scripts {
    <!--Scripts.Render("~/bundles/jqueryval")-->
    <!--Scripts.Render("~/bundles/mapacreate")-->
}

ProyectoVikingsGen/MvcApplication1/Views/BatallaPVP/Delete.cshtml
@model MvcApplication1.Models.BatallaPVP

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Seguro que quiere Eliminar esto?</h3>
<fieldset>
    <legend>Evento</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.IdGanador)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IdGanador
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Jugador1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Jugador1.Nombre)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Precio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Precio)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Creador)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Creador)
    </div>

</fieldset>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Volver a todas Batallas ", "List")
    </p>
}

ProyectoVikingsGen/MvcApplication1/Views/BatallaPVP/Details.cshtml
@model MvcApplication1.Models.BatallaPVP

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles @Html.DisplayFor(model => model.id)</h2>

<fieldset>
    <legend>BatallaPVP</legend>

   
    <div class="display-field">
        @Html.DisplayFor(model => model.IdGanador)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Recompensa)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Jugador1.Nombre)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Jugador2)
    </div>
   

</fieldset>

<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Crear", "Create", new { id = Model.id }, "null") |
    @Html.ActionLink("Ver Jugador2", "Details", "Jugador2", new { id = Model.id }, "null") |
    @Html.ActionLink("Todos las Batallas PVE", "List") |
    @Html.ActionLink("Ver Jugador1", "Details", "Jugador1", new { id = Model.id }, "null") |
    @Html.ActionLink("Indice", "Index")
    
</p>

ProyectoVikingsGen/MvcApplication1/Views/BatallaPVP/Index.cshtml
@model IEnumerable<ProyectoVikingsGenNHibernate.EN.ProyectoVikings.Batalla_PVPEN>

@{
    ViewBag.Title = "BatallaPVPs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>BatallaPVPs</h2>

<p>
    @Html.ActionLink("Nuevo BatallaPVP", "Create")
</p>
<p>
    @Html.ActionLink("Mis BatallaPVPs", "List")
</p>
<table>
    <tr>
        
        <th>
            @Html.DisplayNameFor(model =>model.Jugador)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                
                @Html.DisplayFor(modelItem => item.Jugador.Nombre)
            </td>
            
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.Id }) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.Id }) |
                @Html.ActionLink("Ver Jugador1", "Details", "Jugador1", new { id = item.Id }, "null") |
                @Html.ActionLink("Ver Jugador2", "Details", "Jugador2", new { id = item.Id }, "null")

            </td>

        </tr>
    }

</table>

ProyectoVikingsGen/MvcApplication1/Views/BatallaPVP/List.cshtml
@model IEnumerable<ProyectoVikingsGenNHibernate.EN.ProyectoVikings.BatallaPVPEN>

@{
    ViewBag.Title = "Mis BatallaPVPs";
}

<h2>Mis BatallaPVPs</h2>

<p>
    @Html.ActionLink("Nuevo BatallaPVP", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdGanador)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Recompensa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Jugador1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Jugador2)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdGanador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Recompensa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Jugador1.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Jugador2.Nombre)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.Id}) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.Id }) |
                @Html.ActionLink("Ver Jugador1", "Details", "Jugador1", new { id = item.Id }, "null") |
                @Html.ActionLink("Ver Jugador2", "Details", "Jugador2", new { id = item.Id }, "null")



            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Volver a BatallaPVPs", "Index")
</div>