ProyectoVikingsGen/MvcApplication1/Controllers/MonstruoController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

using ProyectoVikingsGenNHibernate.CAD.ProyectoVikings;
using ProyectoVikingsGenNHibernate.CEN.ProyectoVikings;
using ProyectoVikingsGenNHibernate.CP.ProyectoVikings;
using ProyectoVikingsGenNHibernate.EN.ProyectoVikings;

namespace MvcApplication1.Controllers
{
    [Authorize(Roles = "usuario")]
    public class MonstruoController : BasicController
    {
        //
        // GET: /BatallaPVE/

        public ActionResult Index()
        {
            SessionInitialize();
            MonstruoCAD cad = new MonstruoCAD(session);
            var aux = cad.ReadAllDefault(0, 0);

            SessionClose();

            return View(aux);
        }

        //
        // GET: /BatallaPVE/Details/5

        public ActionResult Details(int id)
        {
            Monstruo ev = null;
            SessionInitialize();
            MonstruoEN evEN = new MonstruoCAD(session).ReadOIDDefault(id);
            ev = new AssemblerMonstruo().ConvertEnToModelUI(evEN);
            SessionClose();
            return View(ev);
        }

        //
        // GET: /BatallaPVE/Create

        public ActionResult Create()
        {

            SessionInitialize();
            //muy posiblemente si falla, es por esto
            Monstruo ev = new Monstruo();
            

            SessionClose();
            return View(ev);
        }

        //
        // POST: /BatallaPVE/Create

        [HttpPost]
        public ActionResult Create(Monstruo ev)
        {
            try
            {
                JugadorCAD cad = new JugadorCAD();
                MonstruoCEN cen = new MonstruoCEN();
                MonstruoEN even = new MonstruoEN();
                even.Ataque= ev.Ataque;
                even.Defensa= ev.Defensa;
                even.Vida = ev.Vida;
                even.Nombre = ev.Nombre;

                
                cen.New_(even.Nombre, even.Vida, ev.Ataque, ev.Defensa);

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }


        //
        // GET: /Monstruo/Edit/5

        public ActionResult Edit(int id)
        {
            Monstruo ev = null;
            SessionInitialize();
            MonstruoEN even = new MonstruoCAD(session).ReadOIDDefault(id);
            ev = new AssemblerMonstruo().ConvertEnToModelUI(even);
            SessionClose();
            return View(ev);

        }

        //
        // POST: /Monstruo/Edit/5

        [HttpPost]
        public ActionResult Edit(Monstruo ev)
        {
            try
            {
                MonstruoCEN cen = new MonstruoCEN();

                cen.Modify(ev.id, ev.Nombre, ev.Vida,ev.Ataque,ev.Defensa);
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Monstruo/Delete/5

        public ActionResult Delete(int id)
        {
            Monstruo ev = null;
            SessionInitialize();
            MonstruoEN even = new MonstruoCAD(session).ReadOIDDefault(id);
            ev = new AssemblerMonstruo().ConvertEnToModelUI(even);
 
            SessionClose();
            return View(ev);
        }

        //
        // POST: /Monstruo/Delete/5

        [HttpPost]
        public ActionResult Delete(Monstruo ev)
        {
            try
            {

                MonstruoCEN cen = new MonstruoCEN();
                cen.Destroy(ev.id);


                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Monstruo/List

        public ActionResult List()
        {
            SessionInitialize();
            MonstruoCAD cad = new MonstruoCAD(session);

            var aux = cad.ReadAllDefault(0,0);

            SessionClose();

            return View(aux);
        }
    }
}

ProyectoVikingsGen/MvcApplication1/Views/Monstruo/Create.cshtml
@model MvcApplication1.Models.Monstruo

@{
    ViewBag.Title = "Nuevo Monstruo";
}

<h2>Nuevo Monstruo</h2>

@using (Html.BeginForm("Create", "Monstruo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    //id, recompensa, tipoGanador
    <fieldset>
        <legend>Monstruo</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.id)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.id)
            @Html.ValidationMessageFor(model => model.id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Vida)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Vida)
            @Html.ValidationMessageFor(model => model.Vida)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Ataque)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Ataque)
            @Html.ValidationMessageFor(model => model.Ataque)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.Defensa)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Defensa)
            @Html.ValidationMessageFor(model => model.Defensa)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>

     
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<!--h3>Mapa</h3>-->

<div>
    @Html.ActionLink("Volver a Monstruos", "Index")
</div>

@section Scripts {
    <!--Scripts.Render("~/bundles/jqueryval")-->
    <!--Scripts.Render("~/bundles/mapacreate")-->
}

ProyectoVikingsGen/MvcApplication1/Views/Monstruo/Delete.cshtml
@model MvcApplication1.Models.Monstruo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Seguro que quiere Eliminar esto?</h3>
<fieldset>
    <legend>Evento</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Batalla_PVE)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Batalla_PVE.Nombre)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Precio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Precio)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Creador)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Creador)
    </div>

</fieldset>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Volver a todos los Monstruos ", "List")
    </p>
}

ProyectoVikingsGen/MvcApplication1/Views/Monstruo/Details.cshtml
@model MvcApplication1.Models.Monstruo

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles @Html.DisplayFor(model => model.id)</h2>

<fieldset>
    <legend>Monstruo</legend>

   
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Vida)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Ataque)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Defensa)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Batalla_PVE.Nombre)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Monstruo)
    </div>
   

</fieldset>

<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Crear", "Create", new { id = Model.id }, "null") |
    @Html.ActionLink("Ver Monstruo", "Details", "Monstruo", new { id = Model.id }, "null") |
    @Html.ActionLink("Todos las Batallas PVE", "List") |
    @Html.ActionLink("Ver Batalla_PVE", "Details", "Batalla_PVE", new { id = Model.id }, "null") |
    @Html.ActionLink("Indice", "Index")
    
</p>

ProyectoVikingsGen/MvcApplication1/Views/Monstruo/Index.cshtml
@model IEnumerable<ProyectoVikingsGenNHibernate.EN.ProyectoVikings.MonstruoEN>

@{
    ViewBag.Title = "Monstruos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Monstruos</h2>

<p>
    @Html.ActionLink("Nuevo Monstruo", "Create")
</p>
<p>
    @Html.ActionLink("Mis Monstruos", "List")
</p>
<table>
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.Batalla_PVE.Nombre)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Batalla_PVE.Nombre)
            </td>
            
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.Id }) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.Id }) |
                @Html.ActionLink("Ver Batalla_PVE", "Details", "EqBatalla_PVEuipo", new { id = item.Id }, "null") |
                @Html.ActionLink("Ver Monstruo", "Details", "Monstruo", new { id = item.Id }, "null")

            </td>

        </tr>
    }

</table>

ProyectoVikingsGen/MvcApplication1/Views/Monstruo/List.cshtml
Vida@model IEnumerable<ProyectoVikingsGenNHibernate.EN.ProyectoVikings.MonstruoEN>

@{
    ViewBag.Title = "Mis Monstruos";
}

<h2>Mis Monstruos</h2>

<p>
    @Html.ActionLink("Nuevo Monstruo", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vida)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ataque)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Defensa)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vida)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ataque)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Defensa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Batalla_PVE.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Monstruo.Nombre)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.Id}) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.Id }) |
                @Html.ActionLink("Ver Batalla_PVE", "Details", "Batalla_PVE", new { id = item.Id }, "null") |
                @Html.ActionLink("Ver Monstruo", "Details", "Monstruo", new { id = item.Id }, "null")



            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Volver a Monstruos", "Index")
</div>