ProyectoVikingsGen/MvcApplication1/Controllers/BatallaPVEController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

using ProyectoVikingsGenNHibernate.CAD.ProyectoVikings;
using ProyectoVikingsGenNHibernate.CEN.ProyectoVikings;
using ProyectoVikingsGenNHibernate.CP.ProyectoVikings;
using ProyectoVikingsGenNHibernate.EN.ProyectoVikings;

namespace MvcApplication1.Controllers
{
    [Authorize(Roles = "usuario")]
    public class BatallaPVEController : BasicController
    {
        //
        // GET: /BatallaPVE/
       
        public ActionResult Index()
        {
            SessionInitialize();
            Batalla_PVECAD cad = new Batalla_PVECAD(session);
            var aux = cad.ReadAllDefault(0, 0);

            SessionClose();

            return View(aux);
        }

        //
        // GET: /BatallaPVE/Details/5

        public ActionResult Details(int id)
        {
            Batalla_PVE ev = null;
            SessionInitialize();
            Batalla_PVEEN evEN = new Batalla_PVECAD(session).ReadOIDDefault(id);
            ev = new AssemblerBatallaPVE().ConvertEnToModelUI(evEN);
            SessionClose();
            return View(ev);
        }

        //
        // GET: /BatallaPVE/Create

        public ActionResult Create()
        {

            SessionInitialize();
            //muy posiblemente si falla, es por esto
            Batalla_PVE ev = new Batalla_PVE();
            ev.Jugador.Nombre = User.Identity.Name;

            SessionClose();
            return View(ev);
        }

        //
        // POST: /BatallaPVE/Create

        [HttpPost]
        public ActionResult Create(Batalla_PVE ev)
        {
            try
            {
                JugadorCAD cad = new JugadorCAD();
                Batalla_PVECEN cen = new Batalla_PVECEN();
                Batalla_PVEEN even = new Batalla_PVEEN();
                even.Monstruo = ev.Monstruo;
                even.Recompensa = ev.Recompensa;
                even.TipoGanador = ev.tipoGanador;

                even.Jugador = cad.DameJugadorPorNombre(User.Identity.Name);
                cen.New_(even.Monstruo.Id, even.Jugador.Id, ev.Recompensa, ev.tipoGanador);

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }
    

        //
        // GET: /Batalla_PVE/Edit/5

        public ActionResult Edit(int id)
    {
        Batalla_PVE ev = null;
        SessionInitialize();
        Batalla_PVEEN even = new Batalla_PVECAD(session).ReadOIDDefault(id);
        ev = new AssemblerBatallaPVE().ConvertEnToModelUI(even);
        JugadorEN usu = ev.Jugador;
        if (User.Identity.Name != usu.Nombre && !Roles.IsUserInRole("admin"))                
        {
            return RedirectToAction("Details", new { id = id });
        }
        SessionClose();
        return View(ev);

    }

    //
    // POST: /Batalla_PVE/Edit/5

    [HttpPost]
        public ActionResult Edit(Batalla_PVE ev)
        {
            try
            {
                Batalla_PVECEN cen = new Batalla_PVECEN();

                cen.Modify(ev.id, ev.Recompensa, ev.tipoGanador);
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Batalla_PVE/Delete/5

        public ActionResult Delete(int id)
        {
            Batalla_PVE ev = null;
            SessionInitialize();
            Batalla_PVEEN even = new Batalla_PVECAD(session).ReadOIDDefault(id);
            ev = new AssemblerBatallaPVE().ConvertEnToModelUI(even);
            JugadorEN usu = ev.Jugador;
            if (User.Identity.Name != usu.Nombre && !Roles.IsUserInRole("admin"))
            {
                return RedirectToAction("Details", new { id = id });
            }
            SessionClose();
            return View(ev);
        }

        //
        // POST: /Batalla_PVE/Delete/5

        [HttpPost]
        public ActionResult Delete(Batalla_PVE ev)
        {
            try
            {

                Batalla_PVECEN cen = new Batalla_PVECEN();
                cen.Destroy(ev.id);
                

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Batalla_PVE/List

        public ActionResult List()
        {
            SessionInitialize();
            Batalla_PVECAD cad = new Batalla_PVECAD(session);
            JugadorCAD usucad = new JugadorCAD(session);
            JugadorEN usuen = usucad.DameJugadorPorNombre(User.Identity.Name);
            var aux = cad.ReadAll(0, 0);

            SessionClose();

            return View(aux);
        }
    }
}

ProyectoVikingsGen/MvcApplication1/Views/BatallaPVE/Create.cshtml
@model MvcApplication1.Models.Batalla_PVE

@{
    ViewBag.Title = "Nuevo BatallaPVE";
}

<h2>Nuevo BatallaPVE</h2>

@using (Html.BeginForm("Create", "BatallaPVE", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    //id, recompensa, tipoGanador
    <fieldset>
        <legend>BatallaPVE</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.id)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.id)
            @Html.ValidationMessageFor(model => model.id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Recompensa)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Recompensa)
            @Html.ValidationMessageFor(model => model.Recompensa)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.tipoGanador)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.tipoGanador)
            @Html.ValidationMessageFor(model => model.tipoGanador)
        </div>

     
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<!--h3>Mapa</h3>-->

<div>
    @Html.ActionLink("Volver a BatallaPVEs", "Index")
</div>

@section Scripts {
    <!--Scripts.Render("~/bundles/jqueryval")-->
    <!--Scripts.Render("~/bundles/mapacreate")-->
}

ProyectoVikingsGen/MvcApplication1/Views/BatallaPVE/Delete.cshtml
@model MvcApplication1.Models.Batalla_PVE

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Seguro que quiere Eliminar esto?</h3>
<fieldset>
    <legend>Evento</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.tipoGanador)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.tipoGanador
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Jugador)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Jugador.Nombre)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Precio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Precio)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Creador)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Creador)
    </div>

</fieldset>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Volver a todas Batallas ", "List")
    </p>
}

ProyectoVikingsGen/MvcApplication1/Views/BatallaPVE/Details.cshtml
@model MvcApplication1.Models.Batalla_PVE

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles @Html.DisplayFor(model => model.id)</h2>

<fieldset>
    <legend>Batalla_PVE</legend>

   
    <div class="display-field">
        @Html.DisplayFor(model => model.tipoGanador)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Recompensa)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Jugador.Nombre)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Monstruo)
    </div>
   

</fieldset>

<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Crear", "Create", new { id = Model.id }, "null") |
    @Html.ActionLink("Ver Monstruo", "Details", "Monstruo", new { id = Model.id }, "null") |
    @Html.ActionLink("Todos las Batallas PVE", "List") |
    @Html.ActionLink("Ver Jugador", "Details", "Jugador", new { id = Model.id }, "null") |
    @Html.ActionLink("Indice", "Index")
    
</p>

ProyectoVikingsGen/MvcApplication1/Views/BatallaPVE/Index.cshtml
@model IEnumerable<ProyectoVikingsGenNHibernate.EN.ProyectoVikings.Batalla_PVEEN>

@{
    ViewBag.Title = "BatallaPVEs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>BatallaPVEs</h2>

<p>
    @Html.ActionLink("Nuevo BatallaPVE", "Create")
</p>
<p>
    @Html.ActionLink("Mis BatallaPVEs", "List")
</p>
<table>
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.Jugador)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Jugador.Nombre)
            </td>
            
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.Id }) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.Id }) |
                @Html.ActionLink("Ver Jugador", "Details", "Jugador", new { id = item.Id }, "null") |
                @Html.ActionLink("Ver Monstruo", "Details", "Monstruo", new { id = item.Id }, "null")

            </td>

        </tr>
    }

</table>

ProyectoVikingsGen/MvcApplication1/Views/BatallaPVE/List.cshtml
@model IEnumerable<ProyectoVikingsGenNHibernate.EN.ProyectoVikings.Batalla_PVEEN>

@{
    ViewBag.Title = "Mis BatallaPVEs";
}

<h2>Mis BatallaPVEs</h2>

<p>
    @Html.ActionLink("Nuevo BatallaPVE", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TipoGanador)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Recompensa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Jugador)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Monstruo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TipoGanador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Recompensa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Jugador.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Monstruo.Nombre)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.Id}) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.Id }) |
                @Html.ActionLink("Ver Jugador", "Details", "Jugador", new { id = item.Id }, "null") |
                @Html.ActionLink("Ver Monstruo", "Details", "Monstruo", new { id = item.Id }, "null")



            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Volver a BatallaPVEs", "Index")
</div>