ProyectoVikingsGen/MvcApplication1/Controllers/ObjetoController.cs
using MvcApplication1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

using ProyectoVikingsGenNHibernate.CAD.ProyectoVikings;
using ProyectoVikingsGenNHibernate.CEN.ProyectoVikings;
using ProyectoVikingsGenNHibernate.CP.ProyectoVikings;
using ProyectoVikingsGenNHibernate.EN.ProyectoVikings;

namespace MvcApplication1.Controllers
{
    [Authorize(Roles = "usuario")]
    public class ObjetoController : BasicController
    {
        //
        // GET: /Objeto/

        public ActionResult Index()
        {
            SessionInitialize();
            ObjetoCAD cad = new ObjetoCAD(session);
            var aux = cad.ReadAll(0, 0);

            SessionClose();

            return View(aux);
        }

        //
        // GET: /Objeto/Details/5

        public ActionResult Details(int id)
        {
            Objeto ev = null;
            SessionInitialize();
            ObjetoEN evEN = new ObjetoCAD(session).ReadOIDDefault(id);
            ev = new AssemblerObjeto().ConvertEnToModelUI(evEN);
            SessionClose();
            return View(ev);
        }

        //
        // GET: /Objeto/Create

        public ActionResult Create()
        {

            SessionInitialize();
            //muy posiblemente si falla, es por esto
            Objeto ev = new Objeto();

            SessionClose();
            return View(ev);
        }

        //
        // POST: /Objeto/Create

        [HttpPost]
        public ActionResult Create(Objeto ev)
        {
            try
            {
                JugadorCAD cad = new JugadorCAD();
                ObjetoCEN cen = new ObjetoCEN();
                ObjetoEN even = new ObjetoEN();
                even.Ataque = ev.Ataque;
                even.Defensa = ev.Defensa;
                even.Tipo = ev.Tipo;

                even.Inventario = ev.Inventarios;
                even.Equipo = ev.InventarioEq;
                even.Nombre = ev.Nombre;
                even.Id = ev.id;
                even.Precio = ev.Precio;
                cen.New_(even.Nombre, even.Precio, even.Tipo, even.Ataque, even.Defensa);

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }


        //
        // GET: /Objeto/Edit/5

        public ActionResult Edit(int id)
        {
            Objeto ev = null;
            SessionInitialize();
            ObjetoEN even = new ObjetoCAD(session).ReadOIDDefault(id);
            ev = new AssemblerObjeto().ConvertEnToModelUI(even);

            SessionClose();
            return View(ev);

        }

        //
        // POST: /Objeto/Edit/5

        [HttpPost]
        public ActionResult Edit(Objeto ev)
        {
            try
            {
                ObjetoCEN cen = new ObjetoCEN();

                cen.Modify(ev.id, ev.Nombre, ev.Precio, ev.Tipo, ev.Ataque, ev.Defensa);
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Objeto/Delete/5

        public ActionResult Delete(int id)
        {
            Objeto ev = null;
            SessionInitialize();
            ObjetoEN even = new ObjetoCAD(session).ReadOIDDefault(id);
            ev = new AssemblerObjeto().ConvertEnToModelUI(even);

            SessionClose();
            return View(ev);
        }

        //
        // POST: /Objeto/Delete/5

        [HttpPost]
        public ActionResult Delete(Objeto ev)
        {
            try
            {

                ObjetoCEN cen = new ObjetoCEN();
                cen.Destroy(ev.id);


                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Objeto/List

        public ActionResult List()
        {
            SessionInitialize();
            ObjetoCAD cad = new ObjetoCAD(session);

            var aux = cad.ReadAllDefault(0, 0);

            SessionClose();

            return View(aux);
        }
    }
}

ProyectoVikingsGen/MvcApplication1/Views/Objeto/Create.cshtml
@model MvcApplication1.Models.Objeto

@{
    ViewBag.Title = "Nuevo Objeto";
}

<h2>Nuevo Objeto</h2>

@using (Html.BeginForm("Create", "Objeto", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    //id, recompensa, tipoGanador
    <fieldset>
        <legend>Objeto</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.id)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.id)
            @Html.ValidationMessageFor(model => model.id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Precio)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Precio)
            @Html.ValidationMessageFor(model => model.Precio)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Tipo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Tipo)
            @Html.ValidationMessageFor(model => model.Tipo)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.Ataque)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Ataque)
            @Html.ValidationMessageFor(model => model.Ataque)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.Defensa)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Defensa)
            @Html.ValidationMessageFor(model => model.Defensa)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nombre)
            @Html.ValidationMessageFor(model => model.Nombre)
        </div>

     
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<!--h3>Mapa</h3>-->

<div>
    @Html.ActionLink("Volver a Objetos", "Index")
</div>

@section Scripts {
    <!--Scripts.Render("~/bundles/jqueryval")-->
    <!--Scripts.Render("~/bundles/mapacreate")-->
}

ProyectoVikingsGen/MvcApplication1/Views/Objeto/Delete.cshtml
@model MvcApplication1.Models.Objeto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Seguro que quiere Eliminar esto?</h3>
<fieldset>
    <legend>Evento</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Equipo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Equipo.Nombre)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Fecha)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fecha)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Precio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Precio)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Creador)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Creador)
    </div>

</fieldset>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Volver a todos los Objetos ", "List")
    </p>
}

ProyectoVikingsGen/MvcApplication1/Views/Objeto/Details.cshtml
@model MvcApplication1.Models.Objeto

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles @Html.DisplayFor(model => model.id)</h2>

<fieldset>
    <legend>Objeto</legend>

   
    <div class="display-field">
        @Html.DisplayFor(model => model.Nombre)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Precio)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Tipo)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Ataque)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Defensa)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Equipo.Nombre)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Inventario)
    </div>
   

</fieldset>

<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Crear", "Create", new { id = Model.id }, "null") |
    @Html.ActionLink("Ver Inventario", "Details", "Inventario", new { id = Model.id }, "null") |
    @Html.ActionLink("Todos las Batallas PVE", "List") |
    @Html.ActionLink("Ver Equipo", "Details", "Equipo", new { id = Model.id }, "null") |
    @Html.ActionLink("Indice", "Index")
    
</p>

ProyectoVikingsGen/MvcApplication1/Views/Objeto/Index.cshtml
@model IEnumerable<ProyectoVikingsGenNHibernate.EN.ProyectoVikings.ObjetoEN>

@{
    ViewBag.Title = "Objetos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Objetos</h2>

<p>
    @Html.ActionLink("Nuevo Objeto", "Create")
</p>
<p>
    @Html.ActionLink("Mis Objetos", "List")
</p>
<table>
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.Equipo.Nombre)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Equipo.Nombre)
            </td>
            
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.Id }) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.Id }) |
                @Html.ActionLink("Ver Equipo", "Details", "Equipo", new { id = item.Id }, "null") |
                @Html.ActionLink("Ver Inventario", "Details", "Inventario", new { id = item.Id }, "null")

            </td>

        </tr>
    }

</table>

ProyectoVikingsGen/MvcApplication1/Views/Objeto/List.cshtml
@model IEnumerable<ProyectoVikingsGenNHibernate.EN.ProyectoVikings.ObjetoEN>

@{
    ViewBag.Title = "Mis Objetos";
}

<h2>Mis Objetos</h2>

<p>
    @Html.ActionLink("Nuevo Objeto", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tipo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ataque)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Defensa)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ataque)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Defensa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Equipo.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Inventario.Nombre)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.Id}) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.Id }) |
                @Html.ActionLink("Ver Equipo", "Details", "Equipo", new { id = item.Id }, "null") |
                @Html.ActionLink("Ver Inventario", "Details", "Inventario", new { id = item.Id }, "null")



            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Volver a Objetos", "Index")
</div>